### ISSUE TITLE
Token spotted

### ISSUE THREAD

**Issue by Wrench56** [raviolisgithub/aa#1]
Hey!
Your code exposes your Discord bot token! (Line 24)
```py
client.run('MTAwODM0MjQxNjE0MDU0NjA1OA.GMGk5V.t0FPjUIyHexxsuoWGWa-3t3ISywUnZCC7ALEEc')
```
You should definitely reset your API key/token! You should be also using Github's encrypted secrets. Here is [their tutorial](https://docs.github.com/en/actions/security-guides/encrypted-secrets) on this topic.

**Comment by raviolisgithub** [comment]
@Wrench56 omg thanks!! I actually forgot to hide it... TYSM!
